name: test

on:
  push: {}

jobs:
  test:
    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@master
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: |
          yarn install
          yarn tsc
          yarn test:coverage
          yarn codecov -t $CODECOV_TOKEN
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
